name = "yaeos_SL"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "a.nicolah@gmail.com"
copyright = "Copyright 2024, Jane Doe"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
yaeos = { git = "https://github.com/ipqa-research/yaeos.git" }
stdlib = "*"


